### ISSUE TITLE
Questions about "IsNew" and "Save"

### ISSUE THREAD

**Issue by mmoore99** [CollaboratingPlatypus/PetaPoco#10]
Am I correct to assume that  "IsNew" and "Save" will only work properly if the database is using an auto generating primary key?

If the the database is using a "natural" primary key like an invoice number that is being created by the program then that property will be populated by the program when the object is created and the IsNew function will return false (because the primary key is populated) even though the record is not already in the database.  Therefore,  "Save" will not work properly.

Am I understandingt that correctly?  If so, are there any plans to have these functions work with "natural" primary keys?

**Comment by matthewsheeran** [comment]
Yep I hit this one too and had to write an alternate Save() that checks an Exists() on the PK value before deciding to do the update or insert.  Mind you my PK is a VARCHAR and not an AUTO INCREMENT so methinks that you must be caching the largest autoincrement which is why IsNew() does sweet FA i.e. doesn't query the database that I can see BUT now I do entirely understand why! ;-)

And yes Insert and Update work as long as I don't insert a false for AutoIncrement in the parameter list for the former.

Upsert() anyone that does what I am doing above with Exists on a specified PK?
