### ISSUE TITLE
Sql class cache problem (Build once)

### ISSUE THREAD

**Issue by guillaume86** [CollaboratingPlatypus/PetaPoco#106]
In the Sql class, the final sql command and parameters are stored once by the Build() method when trying to access SQL or Parameters and never rebuild after.

So if we access one of them method (firing Build()) and then make an Append(), the request is not correct anymore.

**Comment by pynej** [comment]
This is a major issue.  It also means that if you ever run any interim logging before the final SQL is generated the build SQL will be permeant and never rebuilt.  In addition if you add any Sql object to you watch window or any other debug profiling on nit then the code won't execute the same and when not debugging the code.  This is a MAJOR problem as simply debuging code and stepping through line by line should not produce different results.  

The Build needs to called correctly, or the finalSql fields cleared correctly when any fields are changed.  I'm not sure if the mentioend change to Append will fix the problem in all cases. 

Lets jsut say I wasted the better part of a day because I would never have expected simple debug-stepping to alter the cod logic.

**Comment by pleb** [comment]
@pynej are you saying it should be re-runable? And because it's not, this is a bug?

**Comment by pynej** [comment]
its not so much that you can or can't re-run it.  It's that if you touch the .SQL property for any reason, writing it to a log before the query, or by inspecting it with a  tracer or in the debug tools, they it makes that value permanent and additional calls to append to it don't do anything.  Ie the following should not work:

```var sql = new Sql().Select("field");
Console.WriteLine(sql.SQL); // SELECT field
sql.From("myTable")
Console.WriteLine(sql.SQL); // SELECT field FROM myTable
sql.Where("id = @0", 1)
Console.WriteLine(sql.SQL); // SELECT field FROM myTable WHERE id = @0```

Granted one would not normally log things this way, but this is effectively what happens if you try to step through the SQL calls line by line in the debugger for example.  Instead of that though with the way the cack is build you get the following:

```var sql = new Sql().Select("field");
Console.WriteLine(sql.SQL); // SELECT field
sql.From("myTable")
Console.WriteLine(sql.SQL); // SELECT field
sql.Where("id = @0", 1)
Console.WriteLine(sql.SQL); // SELECT field```

So this doesn't technically prevent any normal operations, but if is very confusing for anyone that tries to trace through their code and observe the SQL as it is built.

**Comment by pleb** [comment]
Ah I see. Yeah that's not right and we should fix it. I might get some time over the next few days to look at it. Or if you want to have a go, please don't hesitate.

**Comment by pleb** [comment]
Ok the unit test that proves this bug. @pynej  thanks ;) 

       [Fact]
        [Description("Investigation of reported bug #106")]
        public void Sql_CacheShouldBeResetAfterAdditionalChanges_ShouldBeValid()
        {
            _sql.Select("field");
            var sqlCapture1 = _sql.SQL;
            _sql.From("myTable");
            var sqlCapture2 = _sql.SQL;
            _sql.Where("id = @0", 1);
            var sqlCapture3 = _sql.SQL;

            sqlCapture1.ShouldBe("SELECT field");
            sqlCapture2.ShouldBe("SELECT field FROM myTable");
            sqlCapture3.ShouldBe("SELECT field FROM myTable WHERE id = @0");
        }

**Comment by pleb** [comment]
Actually the unit test was wrong. 

This one, however, works.

        [Fact]
        [Description("Investigation of reported bug #106")]
        public void Sql_CacheShouldBeResetAfterAdditionalChanges_ShouldBeValid()
        {
            _sql.Select("field");
            var sqlCapture1 = _sql.SQL;
            _sql.From("myTable");
            var sqlCapture2 = _sql.SQL;
            _sql.Where("id = @0", 1);
            var sqlCapture3 = _sql.SQL;

            sqlCapture1.Replace("\n", " ").ShouldBe("SELECT field");
            sqlCapture2.Replace("\n", " ").ShouldBe("SELECT field FROM myTable");
            sqlCapture3.Replace("\n", " ").ShouldBe("SELECT field FROM myTable WHERE (id = @0)");
        }

@pynej Am I missing something, because by my understanding this shouldn't work?

Also, could this be related to #123?

**Comment by pleb** [comment]
@pynej I think this was fixed with 

https://github.com/CollaboratingPlatypus/PetaPoco/commit/fe7d7bb41df5c7c9f3bc94bf165d6ffa5dbe6211#diff-67cd1e6be384082296a81257c1fe46b5

I'm wondering if you're using an older version?

**Comment by mabakay** [comment]
Wow! After 37 months however (my) fix applied and after next 7 project member accepted it!

**Comment by pleb** [comment]
@mabakay Sorry - I think I ported this from npoco after I took over maintenance. But, yes, essentially the same as what you proposed.

**Comment by pynej** [comment]
@pleb Ah, yes this patch does fix it.  Sorry I missed that and didn't realize that the code I was testing was a older version.  I have tested with the correct current code witch has that line and it works as expected.

**Comment by pynej** [comment]
This issue should be closable now.

**Comment by pleb** [comment]
Ok. Good to see we got this sorted out.
