### ISSUE TITLE
Database should expose a CreateParameter method

### ISSUE THREAD

**Issue by grcodemonkey** [CollaboratingPlatypus/PetaPoco#122]
The database class should expose a CreateParameter method that uses the underlying DbProviderFactory.CreateParameter() method to create parameters for scenarios like Output parameters.

This would provide better support for being provider agnostic when using Input/Output parameters.

```
    public IDbDataParameter CreateParameter()
    {
        return _factory.CreateParameter();
    }
```

**Comment by MikeBeaton** [comment]
This suggestion seems simple to create and potentially very useful, at least for those - apparently few! - of us who use database parameters a lot. Though *maybe* there [should be more](https://rob.conery.io/2015/02/20/its-time-to-get-over-that-stored-procedure-aversion-you-have/) of us?! 😉

Anyway... with this proposed update, you could convert from needing this code:

```c#
// NB not database agnostic (uses System.Data.SqlClient)
using (var db = new Database(ConnectionStrings.AdventureWorks, "System.Data.SqlClient"))
{
    var c = new SqlParameter("c", 0);
    c.Direction = ParameterDirection.ReturnValue;
    db.ExecuteNonQueryProc("my_add_proc",
        new SqlParameter("a", 1), new SqlParameter("b", 2), c);
    Assert.AreEqual(3, c.Value);
}
```

to using this code:

```c#
// NB database agnostic (no dependence on System.Data.SqlClient)
using (var db = new Database(ConnectionStrings.AdventureWorks, "System.Data.SqlClient"))
{
    var c = db.CreateParameter("c", 0, ParameterDirection.ReturnValue);
    db.ExecuteNonQueryProc("my_add_proc",
        db.CreateParameter("a", 1), db.CreateParameter("b", 2), c);
    Assert.AreEqual(3, c.Value);
}
```

I've slightly upgraded the original suggestion to include passing optional name, value and direction, which seem the right things to include.

This would seem genuinely trivial to implement, and relatively simple to add tests for. Would there be any obvious objection to it?

(It does seem somewhat related to #501 where - if I understand correctly - parameter names are ignored at the moment, even if in-principle available, when passed to an arbitrary query, though not when passed to a stored procedure? Though obviously this could be done anyway, and would still be useful for more full-blown stored procedure support, even without any changes or upgrades for #501.)

**Comment by asherber** [comment]
You're right that `CreateParameter()` is easy to implement. I would suggest that there should probably be a few different overloads – maybe name, name+value, name+direction, name+value+direction?

Is it a problem that we can't specify type, since the different enums are db-specific?

**Comment by MikeBeaton** [comment]
I was going to suggest something like:

```c#
public static DbParameter CreateParameter(
    this Database db,
    string name = null,
    object value = null,
    ParameterDirection direction = ParameterDirection.Input)
{
    var param = db.Provider.GetFactory().CreateParameter();
    param.Direction = direction;
    if (name != null) param.ParameterName = name;
    if (value != null) param.Value = value;
    return param;
}
```

After providing MySQL support to Massive I've been using Massive, and then my own '[reboot](https://github.com/MightyOrm/Mighty)' (or something) of it a lot, so I'm used to using optional parameters with defaults everywhere - it seems to work well. I actually came here to see how your support for parameters compared with what I've been working on!! But this suggestion seems such an easy win for anyone using PetaPoco with stored procedures/functions.

I'd recommend against allowing setting `DbType`, since it's so often set correctly, implicitly, by setting the `Value` - where it isn't then yes the user would have to create the parameter and set the type on it first, before passing it to the SP call.

For provider specific parameter types and other enums, in that case I think it certainly IS fair to expect the user to have an explicit dependency on the provider library (though you *can* still avoid the explicit dependency with weird reflection work-arounds... but that part of the code certainly isn't provider agnostic at that point!) - but they would always have the choice of creating the dp-specific parameter directly themselves, or using `CreateParameter`, then casting to the db-specific type, and setting the extra properties, either would be fine.

**Comment by asherber** [comment]
Personally, I have mixed feelings about optional parameters; I often prefer a few overloads, and generally (though not exclusively) I think that's the direction this library has taken as well. I'm not sure if @pleb has an official position on this.

**Comment by MikeBeaton** [comment]
If so, then the obvious set might be (), (name, value) and (name, value, direction)?

**Comment by asherber** [comment]
Probably. I don't use parameter objects much myself -- any good reason for (name) or (name, direction)?

**Comment by MikeBeaton** [comment]
Err - I feel like at that point, mightn't the defaults version be much easier? But: yes to (name, direction), for output params; can't think of anything for (name).
