### ISSUE TITLE
Support for Async calls

### ISSUE THREAD

**Issue by DmitryEfimenko** [CollaboratingPlatypus/PetaPoco#141]
It would be awesome if PetaPoco supported asynchronous execution of the Transact-SQL statements

**Comment by pleb** [comment]
I've contact @tmenier. I'd really like to see this in PetaPoco. Ideally, I'd like two interfaces to separate the two. Builds for < 4 would only support non-async etc.

**Comment by eldiosyeldiablo** [comment]
@pleb , do you want someone to take a stab at implementing this?
The implementation would have some potentially breaking changes since the interface System.Data.IDbConnection does not expose async method.
Instead that was exposed with abstract class System.Data.Common.DbConnection.

These lines in Database.cs would need to change:
```csharp
public Database(IDbConnection connection) {}
public IDbConnection Connection { get; }
private IDbConnection _sharedConnection;
```

**Comment by pleb** [comment]
@eldiosyeldiablo 

Yes, yes, and some more yes!!!

@tmenier has a [fork of PetaPoco](https://github.com/tmenier/AsyncPoco) that is only async. I've spoken with him before and he seems like a reasonable guy, so I don't think he'd take issue with you referencing his source - if needed.

Regarding the .net versions, I think it's time to drop support for 4.0 and to roll with 4.5.* and 4.6.*. I don't foresee any issue with having the project target 4.6.* and compile to both 4.5.* and 4.6.*

**Comment by picasso566** [comment]
I vote yes as well. The only issue I have with using AsyncPoco is that there is more active development, bug fixes and testing going on with this trunk.

**Comment by tmenier** [comment]
AsyncPoco is not "abandonware", I'll still respond to bugs and other requests but they've been few and far between, so I have no plans for major new features, so I consider it by and large "done". Also, I still believe in MS's guidance that a library should be either sync or async, not both, which is why I forked in the first place. Brad Robinson (PetaPoco's creator) agreed with that approach. I don't think there's anything wrong with PP being sync only, and if anyone would like to get involved in AsyncPoco as a contributor they are more than welcome.

That said, AsyncPoco is MIT licensed so you can feel free to use it as you wish.

**Comment by pleb** [comment]
@tmenier I have to disagree with the understanding of the MS guidance. 

I believe that what is meant by this is that when developing an application (end-product) the choice should be either async or sync. This is because the two don't easily mix and doing so will most likely result thread related bugs, such as unexpected locking. 

However, given PetaPoco is not an end-product but a component library, both async and sync APIs should be provided. The primary reason for this is that an end-product should not have to choose what components they can use based on whether the component has chosen to be async or sync. MS themselves usually provide both async and non-async, but not always which is annoying (Identity 3 for example).

I believe contracts are the answer here and I think component libraries should split async/sync into nicely segregated contracts. Doing this would allow, for instance, IPetaPocoAync or IPetaPoco and ensure only the right APIs are available for use by user.

**Comment by picasso566** [comment]
@tmenier and @pleb make good points, but as far as I'm concerned whether the sync/async versions are in different projects or the same comes down to coordination. I've been following the merges on PetaPoco and see bug fixes and new functionality weekly/monthly. 

For instance the complex primary key feature was recently added to PetaPoco. When does the feature get added to AsyncPoco? 

If my project is fundamentally async I would choose AsyncPoco, but it would be _nice_ if it had the same functionality.

**Comment by tmenier** [comment]
"When does the feature get added to AsyncPoco?"

No one has requested it. At the very least, open an issue. Better still, create a PR. I'm not actively watching pushes to PetaPoco and keeping AsyncPoco in sync with it, but I'd love some help with that. Would you like to contribute?

**Comment by TrevorWesterdahl** [comment]
Just a note: multiple forks are awful... for the reason specified: integrated changes and mixtures of supported features. Four years later, still not addressed?

**Comment by pleb** [comment]
@TrevorWesterdahl if you have time, PetaPoco could really do with some help ;)
