### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by twheelmaker** [CollaboratingPlatypus/PetaPoco#214]
I'm truly excited that this project is picking up steam again.  To the new maintainers, please keep it simple! I love that it came with no dependencies and a single c# file I can step through and understand what's happening. Additional features should be modular via nuget. Please don't turn this lean and mean tool into a monolithic, feature-laden beast.

**Comment by dlwiii** [comment]
Agreed!

**Comment by pleb** [comment]
@twheelmaker and @dlwiii. That's the plan! PetaPoco is beloved by many because one can pick it up and run with it quickly. There's no plans to add {insert come complex feature(s) here}. 

IMO - There's [NPoco](https://github.com/schotime/NPoco) if you need PetaPoco with a little more flair or [MircoLite ORM](https://github.com/TrevorPilley/MicroLite) if you want similar ORM with a more structure code base and nice integration opportunities
