### ISSUE TITLE
Query is running three times

### ISSUE THREAD

**Issue by jovball** [CollaboratingPlatypus/PetaPoco#315]
My queries are showing up as repeating three times when I look at SQL Server Profiler. I'm not doing anything exotic.
`
 var sqlDb = new Database(connectionStringKey);

 var customers = sqlDb.Query<Customer>("SELECT * FROM dbo.Customers WHERE country=@0", country);
`

**Comment by pleb** [comment]
Try it from something like [Linqpad](https://www.linqpad.net/) to eliminate your application.

You might because causing this with a linq statement by accident, so I'd suggest you may want to use `Fetch` and not `Query` as fetch will return a complete collection where as query will yield return the results are you need them.

**Comment by pleb** [comment]
How did you go @jovball?

**Comment by jovball** [comment]
Using Fetch fixed the problem. I don't think I understand the point of Query if this is the result.

**Comment by pleb** [comment]
No worries @jovball 

This might be of help (https://www.jetbrains.com/help/resharper/2016.1/PossibleMultipleEnumeration.html)
