### ISSUE TITLE
Querying LINQ Style no overloads for primarykey

### ISSUE THREAD

**Issue by kpstolk** [CollaboratingPlatypus/PetaPoco#337]
Looking at the [docs](https://github.com/CollaboratingPlatypus/PetaPoco/wiki/Querying-LINQ-Style), there are only overloads with `object primaryKey` for `Exists<T>`, `Single<T>` and `SingleOrDefault<T>` but not (yet?) for `FirstOrDefault<T>`?

`var person = db.FirstOrDefault<Person>(12); // The person or NULL`

Need the docs to be updated or is the overload missing in code?

**Comment by asherber** [comment]
I think the docs were incorrect, so I fixed them. Overloads for `First<T>()` and `FirstOrDefault<T>` that take a primary key value don't make sense, because by definition there will only be 0 or 1 records for that value. `First()` is called when you might have several and just want the first one; if you've got a primary key value you should use `Single<T>` or `SingleOrDefault<T>`.
