### ISSUE TITLE
Error when mapping nested type

### ISSUE THREAD

**Issue by hpposch** [CollaboratingPlatypus/PetaPoco#471]
Hi,

i already searched the internet and also the issues here, but none of the solutions helped me to get my code working.

I have the following classes:

```csharp
public class Class1
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Class2 MyClass { get; set; }
    }

    public class Class2
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }
```

When i now want to query all "Class1" from my Database i get an invalid cast Exception because Int64 can not be cast to "Class2" which is clear.
My question now is how can i tell Petapoco to automatically do this for me on any Entity that has nested classes?
If i can do it with Attributes it would also be fine for me.

I noticed that this works with enums, but not with classes...

Thanks in advance for your help! :)

**Comment by hpposch** [comment]
I forgot to say that i can not use the synthax like it is decribed here: https://github.com/schotime/NPoco/wiki/Mapping-to-Nested-Objects
For example: db.Fetch<Class1, Class2>

This is not possible because i have some Wrapper classes around petapoco and therefore i can only provide the main type that should be fetched from the DB.

**Comment by asherber** [comment]
What does your table structure look like? Is it:

```
TABLE1: ID, Name, Table2ID
TABLE2: ID, Name
```

**Comment by hpposch** [comment]
Hi.
Yes the structure is the same as you posted...

**Comment by asherber** [comment]
The main job of PetaPoco is to map a row of data to a POCO. If you use the syntax in which you specify multiple POCO types, PetaPoco knows how to map each type. But you say you can't use this syntax, which means you want PetaPoco to map multiple types without giving it the information it needs.

I haven't tried, but it's possible that you could work something out with a custom `IMapper`. This mapper would see that you're trying to map an `int` to `Class2` and would perform a subquery to retrieve the data from Table2, populate an object, and assign it to the property in `Class1`. This would not be very performant, because instead of one query that returns all the data, you'd be doing one query for all the Table1 data and then one additional query for each row in Table1. It's also possible that you could do something with `Database.OnExecutedCommand` to grab all the Table2 data at once and use that as part of your mapper.

A better possibility might be to change your wrapper classes. For example, if a wrapper class is given `Class1` as an argument, your wrapper could examine `Class1` via reflection and could see that one of its properties is of type `Class2` -- and would then be able to pass both types into the call to `Query()`.
