### ISSUE TITLE
Dynamic, expandos docs?

### ISSUE THREAD

**Issue by brgrz** [CollaboratingPlatypus/PetaPoco#477]
Readme says

> Like Massive, it now also supports dynamic Expandos too - read more

The link does not work (takes us to TopTen software website). Would like to read more about the dynamic support in PetaPoco if possible (not in the Wiki either).

**Comment by asherber** [comment]
If you don't want to create your own POCOs (maybe you just need a couple of fields), you can query records as `dynamic`. You need to supply a full SQL statement, since there's no object to apply `TableName` or `ColumnName` properties to.
```csharp
using (var db = new Database("MyConnection"))
{
    var record = db.Fetch<dynamic>("SELECT TOP 1 ID, DESCRIPTION FROM MY_TABLE");
    int id = record.ID;
}
```
You can also do the usual things like casting the `dynamic` to a dictionary for indexed access:
```csharp
using (var db = new Database("MyConnection"))
{
    var record = db.Fetch<dynamic>("SELECT TOP 1 ID, DESCRIPTION FROM MY_TABLE");
    var dict = (IDictionary<string, object>)record;
    string description = dict["DESCRIPTION"].ToString();
}
```

**Comment by pleb** [comment]
I'll leave this open as a reminder to add docs for it.
