### ISSUE TITLE
T4 Template Creates 100s of Empty Lines

### ISSUE THREAD

**Issue by tylerthardy** [CollaboratingPlatypus/PetaPoco#503]
**Background:**
Obtained PetaPoco v5.1.306 from NuGet into .NET project, but also present using files from this repo.
Bug present in v5.1.306 but not in v5.1.89.
Issue, replication, cause, and resolution listed here. (No Pull Request; can't integration test.)

**Issue:**
Generating Database.cs from Database.tt adds 3-4 linebreaks after each line of generated code:
![image](https://user-images.githubusercontent.com/17709869/52391910-4b9aa400-2a65-11e9-9d8d-031647ab5e77.png)

**Steps to Replicate:**
1. Use PetaPoco v5.1.306 from NuGet OR from this repo.
2. Generate Database.cs by running Database.tt via Visual Studio.

**Cause:**
End-of-lines in (old) v5.1.89 have a carriage return followed by linefeed (\r\n), while the end-of-lines in v5.1.306 only have a linefeed with no carriage return (\n).
![image](https://user-images.githubusercontent.com/17709869/52391769-a41d7180-2a64-11e9-8556-bc6759fea227.png)

**Resolution:**
Adding a carriage return before the linefeed on every line restores the functionality of v5.1.306 to that of v5.1.89.
![image](https://user-images.githubusercontent.com/17709869/52391943-75ec6180-2a65-11e9-87a7-b80e46c456d6.png)

**Comment by pleb** [comment]
@tylerthardy thanks for the detailed explanation and discovery. Any chance you could make a PR which fixes this?

**Comment by nils-a** [comment]
I can not confirm this issue still exists in the current sources. Is the issue still valid?

**Comment by pleb** [comment]
I'm not sure. I haven't used T4 templates in around 10 years, and never plan on using them again if I can help it. The T4 templates are around for people who love pain :)

**Comment by nils-a** [comment]
I'd vote to close this issue, then. It's abviously fixed in current development.

**Comment by Curlack** [comment]
Saw this one and decided to give it a go since it's up for grabs. Was able to generate the code exactly as we would manually i.e. no extra spaces or ill formatting.
Got little side tracked cause I wanted to test the code generation with a SQLite database, saw it wasn't supported, so added support. Then I fixed the whitespace and formatting inside the T4 templates...

Anyway, long story short, the diff on the PetaPoco.Core.ttinclude file looks horrible. I want to create a pull request, will this be standing in the way?
