### ISSUE TITLE
Asp.Net Core 2.2 Dependency Injection in Startup.cs

### ISSUE THREAD

**Issue by jsodeman** [CollaboratingPlatypus/PetaPoco#547]
Is the following the correct way to integrate PetaPoco into a Asp.Net Core 2.2 project?

In Startup.cs

```
public void ConfigureServices(IServiceCollection services)
{
	var db = DatabaseConfiguration.Build().UsingConnectionString("my connection string").Create();
	services.AddSingleton(db);

}
```

**Comment by asherber** [comment]
I think that should work, but note that the singleton instance will keep your db connection open for as long as your application is running. I think it would be better to have the scope as `Scoped` or `Transient`.

**Comment by jsodeman** [comment]
You're right, I probably want ```Scoped```.  Is this the correct injection syntax?

```
services.AddScoped<IDatabase, Database>(ctx => new Database<SqlServerDatabaseProvider>(config.ConnectionString));
```

Also, with a scoped lifetime I assume I wouldn't use ```using``` blocks, and is there anything special I need to do regarding disposing the Database instance?

**Comment by pleb** [comment]
Yes, you want `Scoped`. You could even roll with `Transient`, but `Scoped` is better for your purpose.

Regarding clean up, as PP implements `IDisposable` it will be cleaned up. But, PP uses the `IDispose` mainly for the `using` statement support, so the "cleaning" is optional.

**Comment by jsodeman** [comment]
Great, thanks for the help.

**Comment by biapar** [comment]
IS there a full example with dispose and call into a repository?

**Comment by pleb** [comment]
@biapar not that I know of. However, there's this question on Stackoverflow which may help https://stackoverflow.com/questions/35136260/petapoco-unit-of-work-repository-pattern

**Comment by asherber** [comment]
I guess a descendant class would be okay -- just keep in mind that I think you'll lose access to the fluent configuration syntax, since that's tied to `Database`. Couldn't hurt to try and see what issues you run into.

Changing a connection string is possible, but a little tricky. `Database.Connection` and `Database.ConnectionString` are both read-only; you can modify properties on `Database.Connection`, but that property is only populated if you created the database by passing in a connection (or if you passed in a connection string and the connection is open, but then of course you can't modify it). So something roughly like this works:

```
SqlConnection myConnection = new SqlConnection();
var db = new Database(myConnection);
db.Connection.ConnectionString = "my new connection string";
```

Note that the connection needs to be closed in order to change the connection string (which is the default state if the database is created as above), and then it needs to be explicitly opened before performing any operations with the database.

**Comment by Ed156** [comment]
Thank you again Aaron, good to know. I made the descendant class and interface with which things seem to work as usual so far. Losing the fluent instantiation is no big loss for me, it is just a few lines.
