### ISSUE TITLE
Support for sap hana database ?

### ISSUE THREAD

**Issue by Suhut** [CollaboratingPlatypus/PetaPoco#565]

**Comment by asherber** [comment]
Sure, I don't see why not, as long as you have the ADO.NET provider for that database. You'll need to write and register your own [custom `DatabaseProvider`](https://github.com/CollaboratingPlatypus/PetaPoco/wiki/Custom-DB-Providers).

**Comment by iadaz** [comment]
I've done exactly that, works a treat in just a dozen lines of code. Couple of gotchas:

1. The ADO provider returns a HanaDecimal rather than a standard Decimal. You might want to use a mapper to convert them.

2. The version number of the provider has to match the Hana ODBC driver version if you're deploying to multiple systems. This is true of anything that uses the SAP provider, not just PetaPoco.

**Comment by Suhut** [comment]
big thanks ya.
it's work.
![image](https://user-images.githubusercontent.com/15138831/71643156-32878b00-2ce8-11ea-81b1-17a47052759f.png)
