### ISSUE TITLE
Question: Table T1 with some fields and similar table t2 plus other field in other Db

### ISSUE THREAD

**Issue by biapar** [CollaboratingPlatypus/PetaPoco#581]
Hi,
I've two db, db1 and db2 with table t1 with some fields and t2 in db2 with the same fields of t1 plus others.
Question: Is't possible to build a class with t1 and t2 fields where a runtime I can target db1 or db2?

**Comment by asherber** [comment]
I think you can do this as long as you don't rely on auto-generated select clauses.

If this is your POCO:
```csharp
class Poco
{
  public string T1Field { get; set; }
  public string AnotherT1Field { get; set; }
  public string T2Field { get; set; }
}
```
If you do `db.Fetch<Poco>()`, the auto-generated SQL will be `SELECT T1Field, AnotherT1Field, T2Field FROM Poco`. If you run this against db1, you'll get an error because `T2Field` doesn't exist there.

But if you do `db.Fetch<Poco>("SELECT T1Field, AnotherT1Field FROM Poco")`, then you're only requesting the fields that exist in db1. Running against db2, you could either use the auto-generated SQL or write your own that includes all fields.

You might find it helpful to use PetaPoco's [SQL builder](https://github.com/CollaboratingPlatypus/PetaPoco/wiki/Building-SQL-Queries), or something more powerful like [SqlKata](https://sqlkata.com) (see also my [PetaPoco extensions](https://github.com/asherber/PetaPoco.SqlKata) for SqlKata).
