### ISSUE TITLE
Support for MySqlConnector

### ISSUE THREAD

**Issue by krugertech** [CollaboratingPlatypus/PetaPoco#586]
Hey guys,

Can we add a new data provider to support [MySqlConnector](https://github.com/mysql-net/MySqlConnector)'s pure ADO.NET provider?

Some pro's of this provider are:
1. The MySqlConnector provider is around 50% faster than the provider supplied by Oracle according to the MySqlConnector folks. 
2.  The MySqlConnector provider does not have a dependency on the Oracle MySql Connector.
3. MySqlConnector folks apparently fixed a some issues still existing in the Oracle MySql provider. 

I've tested creating a new MySqlConnectorDatabaseProvider and added conditional code which auto selects the right MySql provider based on which MySql assemblies are loaded.

[MySqlConnectorDatabaseProvider.cs.txt](https://github.com/CollaboratingPlatypus/PetaPoco/files/4821550/MySqlConnectorDatabaseProvider.cs.txt)
[DatabaseProvider.cs.txt](https://github.com/CollaboratingPlatypus/PetaPoco/files/4821555/DatabaseProvider.cs.txt)

**Comment by iadaz** [comment]
Hi @krugertech, 

I am not one of the PP gurus, but your question piqued my interest because I've got some old code using the Oracle connector and have had all sorts of fun and games with assembly binding when deploying to servers that have different versions of the Oracle connector pre-installed (as well as bugs, of course). I thought I would see how good this alternative was and so I dropped it into an existing project. I only had to change the reference and two lines in the .config file. It just worked.

I know that in the past, suggestions for new built-in connectors don't always get supported because you can always use the provider extensibility anyway, and PRs don't always arrive with a battery of unit tests (and it increases the forward support burden). However, given the lightweight nature of the change required and the fact that (I guess) this requires no new tests, I think I would support this. Plus, anything which encourages the community to supplant the Oracle garbage is probably to be applauded.

**Comment by krugertech** [comment]
Hi @iadaz

>>  I thought I would see how good this alternative was and so I dropped it into an 
>> existing project (though not using PP). I only had to change the reference and two lines in the .config file. It just worked.

Thanks for the feedback. 
I was wondering how people were dealing with having Oracle's connector installed everywhere. 

May I inquire about the 2 lines you changed in the .config in order to get it working ?

The problem I run into is that PP appears to be specifically looking for the Oracle version of MySql.Data (and its public key token).
![image](https://user-images.githubusercontent.com/28920021/86603901-f4279d00-bfa4-11ea-9df7-aea2ce68c269.png)

**Comment by iadaz** [comment]
The project I tried it with wasn't using PetaPoco so I haven't got first-hand experience of that. To use MySqlConnector with PetaPoco now you should just be able to create your own class inheriting from `DatabaseProvider` (which will just be a copy of MySqlDatabaseProvider -  https://github.com/CollaboratingPlatypus/PetaPoco/blob/development/PetaPoco/Providers/MySqlDatabaseProvider.cs) and update the GetFactory parameter. Then pass your new provider into `DatabaseConfiguration.Build()`.

**Comment by pleb** [comment]
Can you submit a PR? 

I'd make a `MySqlConnectorDatabaseProvider` that extends `MySqlDatabaseProvider` and overrides the `GetFactory` method.

You'd also need to update the `DatabaseProvider` class and add support.

Lastly, duplicate the MySqL tests (https://github.com/CollaboratingPlatypus/PetaPoco/tree/development/PetaPoco.Tests.Integration/Databases/MySQL) and add MySqlConnector version

**Comment by pleb** [comment]
I’ve added support for this connector.

Let me know what you think?

https://www.nuget.org/packages/PetaPoco.Compiled/6.0.468-beta

**Comment by Ste1io** [comment]
Is MySQLConnector still considered in beta, or was this issue just overlooked and never closed @pleb? Would be nice to either graduate this provider to stable status, and/or close this as complete. Passes all integration tests from #696.

**Comment by pleb** [comment]
@Ste1io the label is more to tell the feature has been added to the beta build. I've removed the tag :)

**Comment by pleb** [comment]
Closing as this is well and truly is the production build

**Comment by Ste1io** [comment]
> @Ste1io the label is more to tell the feature has been added to the beta build. I've removed the tag :)

That's what I thought, just seemed odd being open still at this point. Cheers.
