### ISSUE TITLE
Performance issues with sp_executesql related to parameter sniffing. Can I get compiled SQL from the builder?

### ISSUE THREAD

**Issue by jsodeman** [CollaboratingPlatypus/PetaPoco#627]
I've been having performance issues getting the COUNT(*) from a query. The call times out at 30 seconds, but the SQL executes instantly in SSMS. After some research it appears that the problem is related to parameter sniffing and the way Petapoco wraps the SQL in a `sp_executesql` call.

I'm using the builder to create the query and I think if I could get a compiled (safe) SQL string to send to db then that will help a lot.

Basically instead of having this go to the DB
```
exec sp_executesql N'SELECT COUNT(*) 
FROM [Users] WHERE CompanyId= @0',N'@0 int',@0=127
go
```

I'd rather have this
```
exec sp_executesql N'SELECT COUNT(*) 
FROM [Users] WHERE CompanyId= 127'
go
```

Or of course `SELECT COUNT(*) FROM [Users] WHERE CompanyId= 127` with no `sp_executesql` at all

Is there a way to get a compiled string from builder that has the parameters replaced? Or is there an alternate builder that you would suggest? I looked at SqlKata and the queries I'm building are fairly complex to convert into the fluent format, and I'm not entirely clear that SqlKata will give me a compiled string in the end either.

**Comment by asherber** [comment]
Couple of things here. First, PetaPoco is not inserting that call to `sp_executesql`. That's happening in the ADO.NET layer before the parameterized query gets sent to the server.

Second, the nature of the performance issue you're seeing makes me think that your field types don't match the type you're passing as a param. In particular, although your example uses an int param, if you've got a string param you should make sure that you're passing in the right string type -- `String` for `nvarchar` and `AnsiString` for `varchar`. If you don't do this, then SQL Server can't use your index on that column and has to do a table scan. (If you think this might be your issue, I can add some sample code.)

Third, if you don't want parameterized SQL, then you should consider not using parameters!

```c#
// instead of 
Sql.Builder.Select("count(*)")
	.From("Users")
	.Where("CompanyID=@0", 127);
	
// you can do
Sql.Builder.Select("count(*)")
	.From("Users")
	.Where("CompanyID=127");
	
// or if you've got the value in a variable
Sql.Builder.Select("count(*)")
	.From("Users")
	.Where($"CompanyID={myID}");
```

Just be aware of all of the usual dangers of inserting raw values instead of using parameters.

**Comment by jsodeman** [comment]
I'd seen the type mismatch mentioned before when I was researching this, but in this case even though the SQL is more complex than my example the parameter is an INT. The query can be built onto with WHERE clauses based on UI filters, but the timeout is occurring with just the base query.

```
SELECT COUNT(L.Id)
FROM dbo.Leads L LEFT JOIN dbo.Assignments A ON L.Id=A.LeadId
JOIN dbo.Companies C ON L.CompanyId = C.Id
LEFT JOIN (SELECT LeadId, Awarded, Id, VendorId FROM dbo.Replies WHERE Awarded=1) W ON L.Id=W.LeadId AND W.VendorId=A.AssignedCompanyId
LEFT JOIN (SELECT COUNT(Id) AS Quotes, LeadId, VendorId FROM dbo.Replies GROUP BY LeadId, VendorId) S ON L.Id=S.LeadId AND S.VendorId=A.AssignedCompanyId WHERE AssignedCompanyId=@0
```

I may try not using parameters for numeric clauses and just use them for strings. I just wanted to make sure I wasn't missing some other approach that I wasn't aware of with the builder.

**Comment by Curlack** [comment]
Try adding an 'Order By' clause. It could be the regular expression scan
that's causing the timeout.

**Comment by asherber** [comment]
Have you tried running your query in straight ADO.NET (SqlConnection, SqlCommand, etc.), with and without parameters, and comparing the query plan in SSMS? That would take PetaPoco out of the picture and let you see if there's a difference in the query execution itself.

**Comment by jsodeman** [comment]
Thank you both. For reasons I don't understand the query is running fast now. When it starts to happen again I'll attempt some deeper debugging as suggested, and try removing the use of parameters in places.
