### ISSUE TITLE
Result column is not selected

### ISSUE THREAD

**Issue by mergoktas** [CollaboratingPlatypus/PetaPoco#660]
This my table and I use ID column with Identity attribute for one purpose, primary column for another purpose.  Therefore ID column is a ResultColumn.

```
CREATE TABLE [dbo].[Table_1](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MyPrimeKey] [nvarchar](20) NOT NULL,
	[MyInt1] [int] NULL,
	[MyInt2] [int] NULL,
 CONSTRAINT [PK_Table_1] PRIMARY KEY CLUSTERED 
(
	[MyPrimeKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
```
and my poco class

`[TableName("[dbo].[Table_1]")]
    [PrimaryKey("MyPrimeKey", AutoIncrement = false)]
    [ExplicitColumns]
    public class Table_1 
    {

        [ResultColumn]
        public int ID
        {
            get { return _ID; }
            set { _ID = value; }
        }
        int _ID;

        [Column]
        public string MyPrimeKey
        {
            get { return _MyPrimeKey; }
            set { _MyPrimeKey = value;  }
        }
        string _MyPrimeKey;

        [Column]
        public int? MyInt1
        {
            get { return _MyInt1; }
            set { _MyInt1 = value; }
        }
        int? _MyInt1;

        [Column]
        public int? MyInt2
        {
            get { return _MyInt2; }
            set { _MyInt2 = value;  }
        }
        int? _MyInt2;

    }`
I added 4 rows to the table. Then when I made  the following queries, ID column is returned zero.

`var list0 = db.Query<Table_1>();
 var list1 = db.Query<Table_1>().ToList();
 var list2 = db.Fetch<Table_1>();`

But for the following query, it does return the correct ID values.

`var list3 = db.Fetch<Table_1>("select * from Table_1");`

Is this the correct behavior or is a bug?

**Comment by asherber** [comment]
This is by design. When you indicate that a column is a result column, PP assumes that it's not coming from the database, so it's not included in auto-generated `SELECT` statements. In other words, when you do `Query<Table_1>`, PP constructs the following `SELECT` statement:

```sql
SELECT MyPrimeKey, MyInt1, MyInt2 FROM Table_1
```

But when you explicitly do `SELECT * FROM Table_1`, all fields are returned and mapped to the appropriate fields in your class.

As [the docs](https://github.com/CollaboratingPlatypus/PetaPoco/wiki/Mapping-Pocos#mapping-attributes) say, if you do want to include a result column in an auto-generated `SELECT`, you need to add `IncludeInAutoSelect.Yes` to the `ResultColumn` attribute.

**Comment by mergoktas** [comment]
Appreciate for your explanation.
Excuse me for not seeing the docs.
Thank you.
