### ISSUE TITLE
update dynamic object will cause exception

### ISSUE THREAD

**Issue by chenruyahoho** [CollaboratingPlatypus/PetaPoco#667]
![021601](https://user-images.githubusercontent.com/38415911/219234921-a92bad03-c85d-4049-87dd-4d020effcba5.png)
![021602](https://user-images.githubusercontent.com/38415911/219234933-ab07a29a-ee73-4213-91a4-680b61d3d079.png)
![021603](https://user-images.githubusercontent.com/38415911/219234938-102f4707-e620-4d38-b7aa-a5815d5f53fc.png)

**Comment by Ste1io** [comment]
@chenruyahoho I apologize for the extended delay in addressing this issue. When I'm at my PC in a few hours I'll try to repro this, but iirc AddParam has a null check for the PocoColumn pc param, but not for the PropertyInfo property in pc which would absolutely cause a null reference exception if null. Since dynamic isn't strongly typed, this would make sense.

I'll take a look later tonight when I can throw together a test case and verify this.

**Comment by Ste1io** [comment]
Ran across this PR, adding it here in case this comes up again down the road:

Related Issue: #251
Related PR: #253
Related PR: #249
